version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev

  app:
    build: .
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0  # Set Redis URL for Rails application
    ports:
      - '3000:3000'
    volumes:
      - ".:/workspace"
    depends_on:
      - mysql
      - redis

  golang-app:
    build:
      context: ./golang_app   # Path to Golang application directory
    ports:
      - "8080:8080"  # Expose Golang server port
    depends_on:
      - mysql
      - redis

volumes:
  dbdata:
