version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # RabbitMQ server port
      - "15672:15672"  # RabbitMQ management console port

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev

  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ".:/workspace"
    depends_on:
      - mysql
      - rabbitmq

  golang-app:
    build:
      context: ./golang_app   # Path to Golang application directory
    ports:
      - "8080:8080"  # Expose Golang server port
    depends_on:
      - mysql
      - rabbitmq


volumes:
  dbdata:
