version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - instabug_chat_system_default

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    networks:
      - instabug_chat_system_default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - instabug_chat_system_default  # Ensure the network name matches

  app:
    build: .
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0  # Set Redis URL for Rails application
      DATABASE_URL: mysql2://root:root@mysql:3306/dev  # MySQL connection
      ELASTICSEARCH_URL: http://elasticsearch:9200  # Elasticsearch connection
    ports:
      - '3000:3000'
    volumes:
      - ".:/workspace"
    depends_on:
      - mysql
      - redis
      - elasticsearch
    networks:
      - instabug_chat_system_default

  golang-app:
    build:
      context: ./golang_app   # Path to Golang application directory
    ports:
      - "8080:8080"  # Expose Golang server port
    depends_on:
      - mysql
      - redis
    networks:
      - instabug_chat_system_default

networks:
  instabug_chat_system_default:
    external: true

volumes:
  dbdata:
